spring:
  application:
    name: weatherApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: aldiyar
    password: 2205
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true

weather:
  api:
    url: http://api.weatherapi.com/v1
    api-key: ${WEATHER_API_KEY}

server:
  port: 8081